# Generated by Django 4.2.1 on 2023-06-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id_berita', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('gambar', models.ImageField(upload_to='berita/')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Koleksi',
            fields=[
                ('id_koleksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('nama_koleksi', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='koleksi/')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id_daftar_pengunjung', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('umum', 'Umum'), ('siswa', 'Siswa'), ('mahasiswa', 'Mahasiswa')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('asal', models.CharField(max_length=255)),
            ],
        ),
    ]
