# Generated by Django 4.2.1 on 2023-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.AutoField(primary_key=True, serialize=False)),
                ('judul_laporan', models.CharField(max_length=100)),
                ('nomor_laporan', models.CharField(max_length=100)),
                ('tanggal_laporan', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(upload_to='user_app/berita/'),
        ),
    ]
