# Generated by Django 4.2.1 on 2023-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_laporan_alter_berita_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(upload_to='berita/'),
        ),
    ]
