# Generated by Django 4.2.1 on 2023-06-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_rating_pengunjung_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengunjung',
            name='email',
        ),
    ]
