# Generated by Django 4.2.1 on 2023-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_delete_laporan_alter_pengunjung_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='koleksi',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
