# Generated by Django 4.2 on 2023-08-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_alter_berita_tanggal_alter_koleksi_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentangMuseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejarah', models.TextField()),
                ('gambar_museum', models.ImageField(upload_to='tentang_museum/')),
                ('visi_misi', models.TextField()),
                ('gambar_struktur_organisasi', models.ImageField(upload_to='struktur_organisasi/')),
            ],
        ),
    ]
