# Generated by Django 4.2 on 2023-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_tentangmuseum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='kategori',
            field=models.CharField(choices=[('umum', 'Umum'), ('asing', 'Asing'), ('siswa_smp', 'Siswa_smp'), ('siswa_sd', 'Siswa_sd'), ('siswa_sma', 'Siswa_sma'), ('mahasiswa', 'Mahasiswa')], max_length=10),
        ),
    ]
