# Generated by Django 4.2 on 2023-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_alter_pengunjung_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='kategori',
            field=models.CharField(choices=[('umum', 'Umum'), ('asing', 'Asing'), ('siswa TK', 'Siswa TK'), ('siswa SD', 'Siswa SD'), ('siswa SMP', 'Siswa SMP'), ('siswa SMA', 'Siswa SMA'), ('mahasiswa', 'Mahasiswa')], max_length=10),
        ),
    ]
