# Generated by Django 4.2 on 2023-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_alter_pengunjung_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangmuseum',
            name='email_museum',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tentangmuseum',
            name='instagram',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tentangmuseum',
            name='nomor_hp',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
