# Generated by Django 4.2 on 2023-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0011_tentangmuseum_email_museum_tentangmuseum_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangmuseum',
            name='alamat',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
