# Generated by Django 4.2 on 2023-08-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_tentangmuseum_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentangmuseum',
            old_name='alamat',
            new_name='alamat_museum',
        ),
    ]
