# Generated by Django 4.2 on 2023-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_rename_alamat_tentangmuseum_alamat_museum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengajuan', models.DateField()),
                ('tanggal_kunjungan', models.DateField()),
                ('no_hp', models.TextField(max_length=15)),
                ('asal_rombongan', models.CharField(max_length=100)),
                ('jumlah_rombongan', models.PositiveIntegerField()),
            ],
        ),
    ]
