# Generated by Django 4.2.1 on 2023-06-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='berita',
            table='kelola_berita',
        ),
    ]
